name: macode101
services:
  postgres:
    image: postgres:15-alpine
    container_name: urlshortener-db
    environment:
      POSTGRES_USER: u_postgres
      POSTGRES_PASSWORD: p_postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
